name: Android Build & Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ghost-tablet-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Release to GitHub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout again
        uses: actions/checkout@v3

      - name: Zip project
        run: zip -r release-bundle.zip . -x "*.git*" "*/build/*"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: Ghost WebView Tablet v1.0
          tag_name: v1.0.0
          files: |
            release-bundle.zip
            app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
